### PR TITLE
Feature - change licence holder awerb

### PR DESCRIPTION
**Pull request by joefitter**
* removed whitelist for change licence holder, now data contains experience qs
* allow profile tasks to be configurable

### CODE REVIEW

**Comment by lennym** [comment]
What's the use case for the bit about skipping related profile tasks?

**Comment by joefitter** [comment]
we get the profile if the `licenceHolderId` is set, to access name, but if we do this we get all related tasks, which basic user doesn't have perms for

**Comment by lennym** [comment]
It looks like that case is kind of handled already in the error handler for that call. Does this actually cause a failure, or is it just for performance gainz?

**Comment by joefitter** [comment]
it throws an error

**Comment by joefitter** [comment]
actually, it logs an error, and then hangs _forever_

**Comment by joefitter** [comment]
hmm the "hanging forever" part may have been from somewhere else.

**Comment by lennym** [comment]
Yeah... I feel like it would be better to find and fix that so that it works like it should rather than needing to be called with a query string to not crash.

**Pull request merged**
