### PR TITLE
Prevent duplicate places being created

### PR DESCRIPTION
**Pull request by wheelsandcogs**

### CODE REVIEW

**Comment by lennym** [comment]
This isn't establishment scoped at the moment and will need to be.

**Comment by lennym** [comment]
Also, we probably want to do this check earlier - at the point of input rather than letting them get a couple of steps along the line before rejecting it.

**Comment by lennym** [comment]
Also also, we will want the same check on amending an area as well as creation.

**Comment by wheelsandcogs** [comment]
Closing for now.

**Pull request closed without merging**
